export const CHART_ANIMATION_MS = 1400
export const CHART_ANIMATION_SECONDS = CHART_ANIMATION_MS / 1000
export const FAST_CHART_ANIMATION_MS = CHART_ANIMATION_MS / 2
export const FAST_CHART_ANIMATION_SECONDS = CHART_ANIMATION_SECONDS / 2
